CREATE TABLE if not exists clientes ( cuit CHAR(11) NOT NULL, razon_social VARCHAR(45) NOT NULL, email VARCHAR(320) NULL, PRIMARY KEY (cuit));

CREATE TABLE if not exists tecnicos ( ID INT NOT NULL, nombre VARCHAR(45) NULL, apellido VARCHAR(45) NULL, email VARCHAR(320) NULL, celular VARCHAR(20) NULL, metodo_notificacion ENUM('email', 'celular') NULL, PRIMARY KEY (ID));

CREATE TABLE if not exists servicios ( ID INT NOT NULL, nombre VARCHAR(45) NOT NULL, PRIMARY KEY (ID));

CREATE TABLE if not exists especialidades ( ID INT NOT NULL, nombre VARCHAR(45) NOT NULL, descripcion VARCHAR(255) NULL, PRIMARY KEY (ID));

CREATE TABLE if not exists tipos_estados ( id INT NOT NULL, nombre VARCHAR(45) NOT NULL, descripcion VARCHAR(255) NULL, PRIMARY KEY (id), UNIQUE INDEX nombre_UNIQUE (nombre ASC) VISIBLE);

CREATE TABLE if not exists incidentes ( ID INT NOT NULL, id_tecnicos INT NOT NULL, id_servicios INT NOT NULL, cuit_clientes CHAR(11) NOT NULL, id_tipos_estados INT NOT NULL, fecha_creacion DATETIME NOT NULL, fecha_resolucion DATETIME NULL, consideraciones VARCHAR(255) NULL, PRIMARY KEY (ID), INDEX id_tecnicos_incidentes_idx (id_tecnicos ASC) VISIBLE, INDEX id_servicios_incidentes_idx (id_servicios ASC) VISIBLE, INDEX cuit_clientes_incidentes_idx (cuit_clientes ASC) VISIBLE, INDEX id_tipos_estados_incidentes_idx (id_tipos_estados ASC) VISIBLE, CONSTRAINT id_tecnicos_incidentes   FOREIGN KEY (id_tecnicos)   REFERENCES tecnicos (ID)   ON DELETE NO ACTION   ON UPDATE NO ACTION, CONSTRAINT id_servicios_incidentes   FOREIGN KEY (id_servicios)   REFERENCES servicios (ID)   ON DELETE NO ACTION   ON UPDATE NO ACTION, CONSTRAINT cuit_clientes_incidentes   FOREIGN KEY (cuit_clientes)   REFERENCES clientes (cuit)   ON DELETE NO ACTION   ON UPDATE NO ACTION, CONSTRAINT id_tipos_estados_incidentes   FOREIGN KEY (id_tipos_estados)   REFERENCES tipos_estados (id)   ON DELETE NO ACTION   ON UPDATE NO ACTION);


CREATE TABLE if not exists tipos_problemas ( ID INT NOT NULL, nombre VARCHAR(45) NOT NULL, tiempo_maximo_resolucion INT NOT NULL, PRIMARY KEY (ID));

CREATE TABLE if not exists problemas ( id INT NOT NULL, id_incidentes INT NOT NULL, id_tipos_problemas INT NOT NULL, id_tipos_estados INT NOT NULL, es_complejo TINYINT NOT NULL, horas_extra_complejo INT NULL, descripcion VARCHAR(255) NULL, PRIMARY KEY (id), INDEX id_incidentes_problemas_idx (id_incidentes ASC) VISIBLE, INDEX id_tipos_problemas_problemas_idx (id_tipos_problemas ASC) VISIBLE, INDEX id_tipos_estados_problemas_idx (id_tipos_estados ASC) VISIBLE, CONSTRAINT id_incidentes_problemas   FOREIGN KEY (id_incidentes)   REFERENCES incidentes (ID)   ON DELETE NO ACTION   ON UPDATE NO ACTION, CONSTRAINT id_tipos_problemas_problemas   FOREIGN KEY (id_tipos_problemas)   REFERENCES tipos_problemas (ID)   ON DELETE NO ACTION   ON UPDATE NO ACTION, CONSTRAINT id_tipos_estados_problemas   FOREIGN KEY (id_tipos_estados)   REFERENCES tipos_estados (id)   ON DELETE NO ACTION   ON UPDATE NO ACTION);


CREATE TABLE if not exists especialidades_x_tecnicos ( id_especialidades INT NOT NULL, id_tecnicos INT NOT NULL, INDEX id_especialidades_idx (id_especialidades ASC) VISIBLE, INDEX id_tecnicos_idx (id_tecnicos ASC) VISIBLE, CONSTRAINT id_especialidades_especialidades_x_tecnicos   FOREIGN KEY (id_especialidades)   REFERENCES especialidades (ID)   ON DELETE NO ACTION   ON UPDATE NO ACTION, CONSTRAINT id_tecnicos_especialidades_x_tecnicos   FOREIGN KEY (id_tecnicos)   REFERENCES tecnicos (ID)   ON DELETE NO ACTION   ON UPDATE NO ACTION);

CREATE TABLE if not exists especialidades_x_tipos_problemas ( id_especialidades INT NOT NULL, id_tipos_problemas INT NOT NULL, INDEX id_especialidades_especialidades_X_tipos_problemas_idx (id_especialidades ASC) VISIBLE, INDEX id_tipos_problemas_especialidades_X_tipos_problemas_idx (id_tipos_problemas ASC) VISIBLE, CONSTRAINT id_especialidades_especialidades_X_tipos_problemas   FOREIGN KEY (id_especialidades)   REFERENCES especialidades (ID)   ON DELETE NO ACTION   ON UPDATE NO ACTION, CONSTRAINT id_tipos_problemas_especialidades_X_tipos_problemas   FOREIGN KEY (id_tipos_problemas)   REFERENCES tipos_problemas (ID)   ON DELETE NO ACTION   ON UPDATE NO ACTION);

CREATE TABLE if not exists servicios_x_clientes ( id_servicios INT NOT NULL, cuit_clientes CHAR(11) NOT NULL, INDEX id_servicios_servicios_x_clientes_idx (id_servicios ASC) VISIBLE, INDEX cuit_clientes_servicios_x_clientes_idx (cuit_clientes ASC) VISIBLE, CONSTRAINT id_servicios_servicios_x_clientes   FOREIGN KEY (id_servicios)   REFERENCES servicios (ID)   ON DELETE NO ACTION   ON UPDATE NO ACTION, CONSTRAINT cuit_clientes_servicios_x_clientes   FOREIGN KEY (cuit_clientes)   REFERENCES clientes (cuit)   ON DELETE NO ACTION   ON UPDATE NO ACTION);

CREATE TABLE if not exists tecnicos_estimacion_tipos_problemas ( id_tecnicos INT NOT NULL, id_tipos_problemas INT NOT NULL, horas_estimadas INT NOT NULL, INDEX id_tecnicos_tecnicos_Estimacion_tipos_problemas_idx (id_tecnicos ASC) VISIBLE, INDEX id_tipos_problemas_tecnicos_Estimacion_tipos_problemas_idx (id_tipos_problemas ASC) VISIBLE, CONSTRAINT id_tecnicos_tecnicos_Estimacion_tipos_problemas   FOREIGN KEY (id_tecnicos)   REFERENCES tecnicos (ID)   ON DELETE NO ACTION   ON UPDATE NO ACTION, CONSTRAINT id_tipos_problemas_tecnicos_Estimacion_tipos_problemas   FOREIGN KEY (id_tipos_problemas)   REFERENCES tipos_problemas (ID)   ON DELETE NO ACTION   ON UPDATE NO ACTION);
